# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import register as module_0


def test_case_0():
    bg_register_0 = module_0.BgRegister()
    assert len(bg_register_0.renderfuncs) == 3
    assert (
        f"{type(bg_register_0.black).__module__}.{type(bg_register_0.black).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.black) == 5
    assert (
        f"{type(bg_register_0.red).__module__}.{type(bg_register_0.red).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.red) == 5
    assert (
        f"{type(bg_register_0.green).__module__}.{type(bg_register_0.green).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.green) == 5
    assert (
        f"{type(bg_register_0.yellow).__module__}.{type(bg_register_0.yellow).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.yellow) == 5
    assert (
        f"{type(bg_register_0.blue).__module__}.{type(bg_register_0.blue).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.blue) == 5
    assert (
        f"{type(bg_register_0.magenta).__module__}.{type(bg_register_0.magenta).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.magenta) == 5
    assert (
        f"{type(bg_register_0.cyan).__module__}.{type(bg_register_0.cyan).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.cyan) == 5
    assert (
        f"{type(bg_register_0.li_grey).__module__}.{type(bg_register_0.li_grey).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.li_grey) == 5
    assert (
        f"{type(bg_register_0.rs).__module__}.{type(bg_register_0.rs).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.rs) == 5
    assert (
        f"{type(bg_register_0.da_grey).__module__}.{type(bg_register_0.da_grey).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.da_grey) == 6
    assert (
        f"{type(bg_register_0.li_red).__module__}.{type(bg_register_0.li_red).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.li_red) == 6
    assert (
        f"{type(bg_register_0.li_green).__module__}.{type(bg_register_0.li_green).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.li_green) == 6
    assert (
        f"{type(bg_register_0.li_yellow).__module__}.{type(bg_register_0.li_yellow).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.li_yellow) == 6
    assert (
        f"{type(bg_register_0.li_blue).__module__}.{type(bg_register_0.li_blue).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.li_blue) == 6
    assert (
        f"{type(bg_register_0.li_magenta).__module__}.{type(bg_register_0.li_magenta).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.li_magenta) == 6
    assert (
        f"{type(bg_register_0.li_cyan).__module__}.{type(bg_register_0.li_cyan).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.li_cyan) == 6
    assert (
        f"{type(bg_register_0.white).__module__}.{type(bg_register_0.white).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.white) == 6
    assert (
        f"{type(bg_register_0.da_black).__module__}.{type(bg_register_0.da_black).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.da_black) == 9
    assert (
        f"{type(bg_register_0.da_red).__module__}.{type(bg_register_0.da_red).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.da_red) == 10
    assert (
        f"{type(bg_register_0.da_green).__module__}.{type(bg_register_0.da_green).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.da_green) == 10
    assert (
        f"{type(bg_register_0.da_yellow).__module__}.{type(bg_register_0.da_yellow).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.da_yellow) == 10
    assert (
        f"{type(bg_register_0.da_blue).__module__}.{type(bg_register_0.da_blue).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.da_blue) == 10
    assert (
        f"{type(bg_register_0.da_magenta).__module__}.{type(bg_register_0.da_magenta).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.da_magenta) == 10
    assert (
        f"{type(bg_register_0.da_cyan).__module__}.{type(bg_register_0.da_cyan).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.da_cyan) == 10
    assert (
        f"{type(bg_register_0.grey).__module__}.{type(bg_register_0.grey).__qualname__}"
        == "primitive.Style"
    )
    assert len(bg_register_0.grey) == 11
