# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import example as module_0


def test_case_0():
    bool_0 = True
    var_0 = module_0.recite(bool_0, bool_0)


def test_case_1():
    bool_0 = False
    var_0 = module_0.recite(bool_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = False
    var_0 = module_0.recite(bool_0)
    bytes_0 = b"\x80\xc7s\xf2\x8f\x18\x0fKV\x18O\x06"
    module_0.recite(bytes_0)


def test_case_3():
    int_0 = 207
    var_0 = module_0.recite(int_0, int_0)
