# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import compat as module_0
import importlib.metadata as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    module_0.find_entry_points(none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.get_dist_name(none_type_0)


def test_case_2():
    selectable_groups_0 = module_1.SelectableGroups()
    iterable_0 = module_0.find_entry_points(selectable_groups_0, selectable_groups_0)
    assert (
        f"{type(iterable_0).__module__}.{type(iterable_0).__qualname__}"
        == "importlib.metadata.EntryPoints"
    )
    assert len(iterable_0) == 0
    assert module_0.is_windows is False
    assert module_0.MIN_SUPPORTED_PY_VERSION == (3, 7)
    assert module_0.MAX_SUPPORTED_PY_VERSION == (3, 11)
