# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import objutils as module_0


def test_case_0():
    str_0 = "o}a"
    bool_0 = module_0.has_any_callables(str_0, *str_0)
    assert bool_0 is False


def test_case_1():
    bool_0 = False
    bool_1 = module_0.has_any_callables(bool_0)


def test_case_2():
    str_0 = "ZjB!|\tvP:8<YB"
    none_type_0 = None
    bool_0 = module_0.has_callables(none_type_0, *str_0)
    assert bool_0 is False


def test_case_3():
    str_0 = "\x0cQbu0@uzhB-)(]1/$"
    bool_0 = module_0.has_callables(str_0)
    assert bool_0 is True


def test_case_4():
    str_0 = "__doc__"
    bool_0 = module_0.has_callables(str_0)
    assert bool_0 is True
    list_0 = [str_0, str_0, str_0, str_0]
    bool_1 = module_0.has_any_callables(str_0)
    list_1 = []
    bool_2 = module_0.has_callables(bool_1, *list_0)
    assert bool_2 is False
    bool_3 = module_0.is_list_like(list_1)
    assert bool_3 is True


def test_case_5():
    bool_0 = True
    bool_1 = module_0.is_list_like(bool_0)
    assert bool_1 is False


def test_case_6():
    str_0 = "__doc__"
    list_0 = [str_0, str_0, str_0, str_0]
    bool_0 = module_0.has_any_callables(str_0, *list_0)
    assert bool_0 is False


def test_case_7():
    str_0 = "__doc__"
    list_0 = [str_0, str_0, str_0, str_0]
    bool_0 = module_0.has_callables(str_0, *list_0)
    assert bool_0 is False
