# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import example as module_0


def test_case_0():
    character_0 = module_0.Character()
    var_0 = character_0.ability()


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b"\xd9\\\xe7"
    module_0.modifier(bytes_0)
