# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import example as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    str_0 = ""
    var_0 = module_0.maximum_value(bool_0, str_0)
    assert var_0 == 0
    list_0 = [str_0, var_0, str_0]
    module_0.maximum_value(bool_0, list_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = 2608
    module_0.maximum_value(int_0, int_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "n^\x0cZ\t_v"
    none_type_0 = None
    module_0.maximum_value(str_0, none_type_0)
