# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import example as module_0
import collections as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    school_0 = module_0.School()
    school_1 = module_0.School()
    var_0 = school_0.add_student(school_1, school_1)
    assert len(school_0.db) == 1
    assert school_0.add == [True]
    var_0.added()


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    none_type_0 = None
    school_0 = module_0.School()
    var_0 = school_0.add_student(bool_0, none_type_0)
    assert school_0.db == {True: None}
    assert school_0.add == [True]
    var_1 = school_0.roster()
    var_1.added()


def test_case_2():
    bytes_0 = b"\x94\x8e\x9b$G\x07!\xe9flkZ"
    school_0 = module_0.School()
    var_0 = school_0.grade(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    school_0 = module_0.School()
    var_0 = school_0.added()
    var_0.roster()


@pytest.mark.xfail(strict=True)
def test_case_4():
    school_0 = module_0.School()
    var_0 = school_0.add_student(school_0, school_0)
    assert len(school_0.db) == 1
    assert school_0.add == [True]
    var_1 = school_0.add_student(school_0, var_0)
    assert school_0.add == [True, False]
    school_1 = module_0.School()
    var_2 = school_0.roster()
    var_3 = school_0.added()
    module_1.defaultdict(**var_3)
