import pytest
from register import ef, fg, bg, rs

def test_EfRegister():
    assert ef.b.render() == '\x1b[1m'
    assert ef.bold.render() == '\x1b[1m'
    assert ef.dim.render() == '\x1b[2m'
    assert ef.i.render() == '\x1b[3m'
    assert ef.italic.render() == '\x1b[3m'
    assert ef.u.render() == '\x1b[4m'
    assert ef.underl.render() == '\x1b[4m'
    assert ef.blink.render() == '\x1b[5m'
    assert ef.inverse.render() == '\x1b[7m'
    assert ef.hidden.render() == '\x1b[8m'
    assert ef.strike.render() == '\x1b[9m'
    assert ef.rs.render() == '\x1b[22m\x1b[23m\x1b[24m\x1b[25m\x1b[27m\x1b[28m\x1b[29m'

def test_FgRegister():
    assert fg.black.render() == '\x1b[30m'
    assert fg.red.render() == '\x1b[31m'
    assert fg.green.render() == '\x1b[32m'
    assert fg.yellow.render() == '\x1b[33m'
    assert fg.blue.render() == '\x1b[34m'
    assert fg.magenta.render() == '\x1b[35m'
    assert fg.cyan.render() == '\x1b[36m'
    assert fg.li_grey.render() == '\x1b[37m'
    assert fg.rs.render() == '\x1b[39m'
    assert fg.da_grey.render() == '\x1b[90m'
    assert fg.li_red.render() == '\x1b[91m'
    assert fg.li_green.render() == '\x1b[92m'
    assert fg.li_yellow.render() == '\x1b[93m'
    assert fg.li_blue.render() == '\x1b[94m'
    assert fg.li_magenta.render() == '\x1b[95m'
    assert fg.li_cyan.render() == '\x1b[96m'
    assert fg.white.render() == '\x1b[97m'
    assert fg.da_black.render() == '\x1b[38;5;0m'
    assert fg.da_red.render() == '\x1b[38;5;88m'
    assert fg.da_green.render() == '\x1b[38;5;22m'
    assert fg.da_yellow.render() == '\x1b[38;5;58m'
    assert fg.da_blue.render() == '\x1b[38;5;18m'
    assert fg.da_magenta.render() == '\x1b[38;5;89m'
    assert fg.da_cyan.render() == '\x1b[38;5;23m'
    assert fg.grey.render() == '\x1b[38;5;249m'

def test_BgRegister():
    assert bg.black.render() == '\x1b[40m'
    assert bg.red.render() == '\x1b[41m'
    assert bg.green.render() == '\x1b[42m'
    assert bg.yellow.render() == '\x1b[43m'
    assert bg.blue.render() == '\x1b[44m'
    assert bg.magenta.render() == '\x1b[45m'
    assert bg.cyan.render() == '\x1b[46m'
    assert bg.li_grey.render() == '\x1b[47m'
    assert bg.rs.render() == '\x1b[49m'
    assert bg.da_grey.render() == '\x1b[100m'
    assert bg.li_red.render() == '\x1b[101m'
    assert bg.li_green.render() == '\x1b[102m'
    assert bg.li_yellow.render() == '\x1b[103m'
    assert bg.li_blue.render() == '\x1b[104m'
    assert bg.li_magenta.render() == '\x1b[105m'
    assert bg.li_cyan.render() == '\x1b[106m'
    assert bg.white.render() == '\x1b[107m'
    assert bg.da_black.render() == '\x1b[48;5;0m'
    assert bg.da_red.render() == '\x1b[48;5;88m'
    assert bg.da_green.render() == '\x1b[48;5;22m'
    assert bg.da_yellow.render() == '\x1b[48;5;58m'
    assert bg.da_blue.render() == '\x1b[48;5;18m'
    assert bg.da_magenta.render() == '\x1b[48;5;89m'
    assert bg.da_cyan.render() == '\x1b[48;5;23m'
    assert bg.grey.render() == '\x1b[48;5;249m'

def test_RsRegister():
    assert rs.all.render() == '\x1b[0m'
    assert rs.fg.render() == '\x1b[39m'
    assert rs.bg.render() == '\x1b[49m'
    assert rs.rs.render() == '\x1b[22m\x1b[23m\x1b[24m\x1b[25m\x1b[27m\x1b[28m\x1b[29m'
    assert rs.bold_dim.render() == '\x1b[22m'
    assert rs.dim_bold.render() == '\x1b[22m'
    assert rs.i.render() == '\x1b[23m'
    assert rs.italic.render() == '\x1b[23m'
    assert rs.u.render() == '\x1b[24m'
    assert rs.underl.render() == '\x1b[24m'
    assert rs.blink.render() == '\x1b[25m'
    assert rs.inverse.render() == '\x1b[27m'
    assert rs.hidden.render() == '\x1b[28m'
    assert rs.strike.render() == '\x1b[29m'