# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import google as module_0


def test_case_0():
    google_parser_0 = module_0.GoogleParser()
    assert (
        f"{type(google_parser_0).__module__}.{type(google_parser_0).__qualname__}"
        == "google.GoogleParser"
    )
    assert (
        f"{type(google_parser_0.sections).__module__}.{type(google_parser_0.sections).__qualname__}"
        == "builtins.dict"
    )
    assert len(google_parser_0.sections) == 12
    assert google_parser_0.title_colon is True
    assert (
        f"{type(google_parser_0.titles_re).__module__}.{type(google_parser_0.titles_re).__qualname__}"
        == "re.Pattern"
    )


def test_case_1():
    none_type_0 = None
    google_parser_0 = module_0.GoogleParser(none_type_0, none_type_0)
    assert (
        f"{type(google_parser_0).__module__}.{type(google_parser_0).__qualname__}"
        == "google.GoogleParser"
    )
    assert (
        f"{type(google_parser_0.sections).__module__}.{type(google_parser_0.sections).__qualname__}"
        == "builtins.dict"
    )
    assert len(google_parser_0.sections) == 12
    assert google_parser_0.title_colon is None
    assert (
        f"{type(google_parser_0.titles_re).__module__}.{type(google_parser_0.titles_re).__qualname__}"
        == "re.Pattern"
    )
    docstring_0 = module_0.parse(none_type_0)
    assert (
        f"{type(docstring_0).__module__}.{type(docstring_0).__qualname__}"
        == "common.Docstring"
    )
    assert docstring_0.short_description is None
    assert docstring_0.long_description is None
    assert docstring_0.blank_after_short_description is False
    assert docstring_0.blank_after_long_description is False
    assert docstring_0.meta == []


def test_case_2():
    str_0 = "~|\nL+"
    docstring_0 = module_0.parse(str_0)
    assert (
        f"{type(docstring_0).__module__}.{type(docstring_0).__qualname__}"
        == "common.Docstring"
    )
    assert docstring_0.short_description == "~|"
    assert docstring_0.long_description == "L+"
    assert docstring_0.blank_after_short_description is False
    assert docstring_0.blank_after_long_description is False
    assert docstring_0.meta == []


def test_case_3():
    none_type_0 = None
    docstring_0 = module_0.parse(none_type_0)
    assert (
        f"{type(docstring_0).__module__}.{type(docstring_0).__qualname__}"
        == "common.Docstring"
    )
    assert docstring_0.short_description is None
    assert docstring_0.long_description is None
    assert docstring_0.blank_after_short_description is False
    assert docstring_0.blank_after_long_description is False
    assert docstring_0.meta == []


def test_case_4():
    str_0 = "nBBg~"
    docstring_0 = module_0.parse(str_0)
    assert (
        f"{type(docstring_0).__module__}.{type(docstring_0).__qualname__}"
        == "common.Docstring"
    )
    assert docstring_0.short_description == "nBBg~"
    assert docstring_0.long_description is None
    assert docstring_0.blank_after_short_description is False
    assert docstring_0.blank_after_long_description is False
    assert docstring_0.meta == []


def test_case_5():
    str_0 = "^\n@"
    google_parser_0 = module_0.GoogleParser(str_0, str_0)
    assert (
        f"{type(google_parser_0).__module__}.{type(google_parser_0).__qualname__}"
        == "google.GoogleParser"
    )
    assert (
        f"{type(google_parser_0.sections).__module__}.{type(google_parser_0.sections).__qualname__}"
        == "builtins.dict"
    )
    assert len(google_parser_0.sections) == 3
    assert google_parser_0.title_colon == "^\n@"
    assert (
        f"{type(google_parser_0.titles_re).__module__}.{type(google_parser_0.titles_re).__qualname__}"
        == "re.Pattern"
    )
    docstring_0 = module_0.parse(str_0)
    assert (
        f"{type(docstring_0).__module__}.{type(docstring_0).__qualname__}"
        == "common.Docstring"
    )
    assert docstring_0.short_description == "^"
    assert docstring_0.long_description == "@"
    assert docstring_0.blank_after_short_description is False
    assert docstring_0.blank_after_long_description is False
    assert docstring_0.meta == []


@pytest.mark.xfail(strict=True)
def test_case_6():
    google_parser_0 = module_0.GoogleParser()
    assert (
        f"{type(google_parser_0).__module__}.{type(google_parser_0).__qualname__}"
        == "google.GoogleParser"
    )
    assert (
        f"{type(google_parser_0.sections).__module__}.{type(google_parser_0.sections).__qualname__}"
        == "builtins.dict"
    )
    assert len(google_parser_0.sections) == 12
    assert google_parser_0.title_colon is True
    assert (
        f"{type(google_parser_0.titles_re).__module__}.{type(google_parser_0.titles_re).__qualname__}"
        == "re.Pattern"
    )
    google_parser_0.add_section(google_parser_0)


def test_case_7():
    str_0 = "\n"
    docstring_0 = module_0.parse(str_0)
    assert (
        f"{type(docstring_0).__module__}.{type(docstring_0).__qualname__}"
        == "common.Docstring"
    )
    assert docstring_0.short_description is None
    assert docstring_0.long_description is None
    assert docstring_0.blank_after_short_description is False
    assert docstring_0.blank_after_long_description is False
    assert docstring_0.meta == []


def test_case_8():
    str_0 = "|\n\x0c"
    docstring_0 = module_0.parse(str_0)
    assert (
        f"{type(docstring_0).__module__}.{type(docstring_0).__qualname__}"
        == "common.Docstring"
    )
    assert docstring_0.short_description == "|"
    assert docstring_0.long_description is None
    assert docstring_0.blank_after_short_description is False
    assert docstring_0.blank_after_long_description is False
    assert docstring_0.meta == []
